import {
  Arbitrum,
  ArbitrumGoerli,
  Avalanche,
  AvalancheFuji,
  Base,
  BaseGoerli,
  CeloAlfajoresTestnet,
  Ethereum,
  Goerli,
  Linea,
  LineaTestnet,
  Mumbai,
  Optimism,
  OptimismGoerli,
  Polygon,
  Sepolia,
} from "@thirdweb-dev/chains";
import { ChainId } from "@thirdweb-dev/sdk";
import dotenv from "dotenv";

dotenv.config();

export const DEFAULT_CHAINS = [
  Ethereum,
  Goerli,
  Sepolia,
  Polygon,
  Mumbai,
  Optimism,
  OptimismGoerli,
  Arbitrum,
  ArbitrumGoerli,
  Avalanche,
  AvalancheFuji,
  Base,
  BaseGoerli,
  Linea,
  LineaTestnet,
  CeloAlfajoresTestnet,
];

export const chainIdToName: Record<number, string> = {
  [ChainId.Mumbai]: "mumbai",
  [ChainId.Goerli]: "goerli",
  [ChainId.Polygon]: "polygon",
  [ChainId.Mainnet]: "mainnet",
  [ChainId.Optimism]: "optimism",
  [ChainId.OptimismGoerli]: "optimism-goerli",
  [ChainId.Arbitrum]: "arbitrum",
  [ChainId.ArbitrumGoerli]: "arbitrum-goerli",
  [ChainId.Avalanche]: "avalanche",
  [ChainId.AvalancheFujiTestnet]: "avalanche-testnet",
  [84531]: "base-goerli",
  [8453]: "base",
};

export const chainIdApiKey: Record<number, string | undefined> = {
  [ChainId.Mumbai]: process.env.POLYGONSCAN_API_KEY || process.env.SCAN_API_KEY,
  [ChainId.Goerli]: process.env.ETHERSCAN_API_KEY || process.env.SCAN_API_KEY,
  [Sepolia.chainId]: process.env.ETHERSCAN_API_KEY || process.env.SCAN_API_KEY,
  [ChainId.Polygon]: process.env.POLYGONSCAN_API_KEY || process.env.SCAN_API_KEY,
  [ChainId.Mainnet]: process.env.ETHERSCAN_API_KEY || process.env.SCAN_API_KEY,
  [ChainId.Optimism]: process.env.OPTIMISM_SCAN_API_KEY || process.env.SCAN_API_KEY,
  [ChainId.OptimismGoerli]: process.env.OPTIMISM_SCAN_API_KEY || process.env.SCAN_API_KEY,
  [ChainId.Arbitrum]: process.env.ARBITRUM_SCAN_API_KEY || process.env.SCAN_API_KEY,
  [ChainId.ArbitrumGoerli]: process.env.ARBITRUM_SCAN_API_KEY || process.env.SCAN_API_KEY,
  [ChainId.Fantom]: process.env.FANTOMSCAN_API_KEY || process.env.SCAN_API_KEY,
  [ChainId.FantomTestnet]: process.env.FANTOMSCAN_API_KEY || process.env.SCAN_API_KEY,
  [ChainId.Avalanche]: process.env.SNOWTRACE_API_KEY || process.env.SCAN_API_KEY,
  [ChainId.AvalancheFujiTestnet]: process.env.SNOWTRACE_API_KEY || process.env.SCAN_API_KEY,
  [ChainId.BinanceSmartChainMainnet]: process.env.BINANCE_SCAN_API_KEY || process.env.SCAN_API_KEY,
  [ChainId.BinanceSmartChainTestnet]: process.env.BINANCE_SCAN_API_KEY || process.env.SCAN_API_KEY,
  [Base.chainId]: process.env.BASE_SCAN_API_KEY || process.env.SCAN_API_KEY,
  [BaseGoerli.chainId]: process.env.BASE_SCAN_API_KEY || process.env.SCAN_API_KEY,
  [Linea.chainId]: process.env.LINEA_SCAN_API_KEY || process.env.SCAN_API_KEY,
  [LineaTestnet.chainId]: process.env.LINEA_SCAN_API_KEY || process.env.SCAN_API_KEY,
};

export const apiMap: Record<number, string> = {
  1: "https://api.etherscan.io/api",
  5: "https://api-goerli.etherscan.io/api",
  [Sepolia.chainId]: "https://api-sepolia.etherscan.io/api",
  10: "https://api-optimistic.etherscan.io/api",
  56: "https://api.bscscan.com/api",
  97: "https://api-testnet.bscscan.com/api",
  137: "https://api.polygonscan.com/api",
  250: "https://api.ftmscan.com/api",
  420: "https://api-goerli-optimistic.etherscan.io/api",
  4002: "https://api-testnet.ftmscan.com/api",
  42161: "https://api.arbiscan.io/api",
  43113: "https://api-testnet.snowtrace.io/api",
  43114: "https://api.snowtrace.io/api",
  421613: "https://api-goerli.arbiscan.io/api",
  80001: "https://api-testnet.polygonscan.com/api",
  84531: "https://api-goerli.basescan.org/api",
  8453: "https://api.basescan.org/api",
  [Linea.chainId]: "https://api.lineascan.build/api",
  [LineaTestnet.chainId]: "https://api-testnet.lineascan.build/api",
};

export const contractsToDeploy = [
  "OpenEditionERC721",
  "DropERC721",
  "DropERC1155",
  "DropERC20",
  "TokenERC20",
  "TokenERC721",
  "TokenERC1155",
  "Split",
  "VoteERC20",
  "NFTStake",
  "TokenStake",
  "EditionStake",
  "AirdropERC20",
  "AirdropERC721",
  "AirdropERC1155",
  "DirectListingsLogic",
  "EnglishAuctionsLogic",
  "OffersLogic",
  "MarketplaceV3",
  // "Forwarder",
  // "TWCloneFactory",
  // "PluginMap",
];
