/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC2981Upgradeable } from "./IERC2981Upgradeable";
export type { IERC5267Upgradeable } from "./IERC5267Upgradeable";
export type { IERC5805Upgradeable } from "./IERC5805Upgradeable";
export type { IERC6372Upgradeable } from "./IERC6372Upgradeable";
