/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  BurnToClaim,
  BurnToClaimInterface,
} from "../../../contracts/extension/BurnToClaim";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "originContract",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "tokenOwner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "burnTokenId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "quantity",
        type: "uint256",
      },
    ],
    name: "TokensBurnedAndClaimed",
    type: "event",
  },
  {
    inputs: [],
    name: "getBurnToClaimInfo",
    outputs: [
      {
        components: [
          {
            internalType: "address",
            name: "originContractAddress",
            type: "address",
          },
          {
            internalType: "enum IBurnToClaim.TokenType",
            name: "tokenType",
            type: "uint8",
          },
          {
            internalType: "uint256",
            name: "tokenId",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "mintPriceForNewToken",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "currency",
            type: "address",
          },
        ],
        internalType: "struct IBurnToClaim.BurnToClaimInfo",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "address",
            name: "originContractAddress",
            type: "address",
          },
          {
            internalType: "enum IBurnToClaim.TokenType",
            name: "tokenType",
            type: "uint8",
          },
          {
            internalType: "uint256",
            name: "tokenId",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "mintPriceForNewToken",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "currency",
            type: "address",
          },
        ],
        internalType: "struct IBurnToClaim.BurnToClaimInfo",
        name: "_burnToClaimInfo",
        type: "tuple",
      },
    ],
    name: "setBurnToClaimInfo",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_tokenOwner",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_tokenId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_quantity",
        type: "uint256",
      },
    ],
    name: "verifyBurnToClaim",
    outputs: [],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class BurnToClaim__factory {
  static readonly abi = _abi;
  static createInterface(): BurnToClaimInterface {
    return new Interface(_abi) as BurnToClaimInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): BurnToClaim {
    return new Contract(address, _abi, runner) as unknown as BurnToClaim;
  }
}
