/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../../common";

export declare namespace IDropClaimCondition_V2 {
  export type ClaimConditionStruct = {
    startTimestamp: BigNumberish;
    maxClaimableSupply: BigNumberish;
    supplyClaimed: BigNumberish;
    quantityLimitPerTransaction: BigNumberish;
    waitTimeInSecondsBetweenClaims: BigNumberish;
    merkleRoot: BytesLike;
    pricePerToken: BigNumberish;
    currency: AddressLike;
  };

  export type ClaimConditionStructOutput = [
    startTimestamp: bigint,
    maxClaimableSupply: bigint,
    supplyClaimed: bigint,
    quantityLimitPerTransaction: bigint,
    waitTimeInSecondsBetweenClaims: bigint,
    merkleRoot: string,
    pricePerToken: bigint,
    currency: string
  ] & {
    startTimestamp: bigint;
    maxClaimableSupply: bigint;
    supplyClaimed: bigint;
    quantityLimitPerTransaction: bigint;
    waitTimeInSecondsBetweenClaims: bigint;
    merkleRoot: string;
    pricePerToken: bigint;
    currency: string;
  };
}

export interface IDropERC1155_V2Interface extends Interface {
  getFunction(
    nameOrSignature:
      | "balanceOf"
      | "balanceOfBatch"
      | "claim"
      | "isApprovedForAll"
      | "lazyMint"
      | "safeBatchTransferFrom"
      | "safeTransferFrom"
      | "setApprovalForAll"
      | "setClaimConditions"
      | "supportsInterface"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ApprovalForAll"
      | "ClaimConditionsUpdated"
      | "MaxTotalSupplyUpdated"
      | "MaxWalletClaimCountUpdated"
      | "SaleRecipientForTokenUpdated"
      | "TokensClaimed"
      | "TokensLazyMinted"
      | "TransferBatch"
      | "TransferSingle"
      | "URI"
      | "WalletClaimCountUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOfBatch",
    values: [AddressLike[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "claim",
    values: [
      AddressLike,
      BigNumberish,
      BigNumberish,
      AddressLike,
      BigNumberish,
      BytesLike[],
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "isApprovedForAll",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lazyMint",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "safeBatchTransferFrom",
    values: [
      AddressLike,
      AddressLike,
      BigNumberish[],
      BigNumberish[],
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "safeTransferFrom",
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setApprovalForAll",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setClaimConditions",
    values: [
      BigNumberish,
      IDropClaimCondition_V2.ClaimConditionStruct[],
      boolean
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "balanceOfBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "claim", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isApprovedForAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "lazyMint", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "safeBatchTransferFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "safeTransferFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setApprovalForAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setClaimConditions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
}

export namespace ApprovalForAllEvent {
  export type InputTuple = [
    account: AddressLike,
    operator: AddressLike,
    approved: boolean
  ];
  export type OutputTuple = [
    account: string,
    operator: string,
    approved: boolean
  ];
  export interface OutputObject {
    account: string;
    operator: string;
    approved: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ClaimConditionsUpdatedEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    claimConditions: IDropClaimCondition_V2.ClaimConditionStruct[]
  ];
  export type OutputTuple = [
    tokenId: bigint,
    claimConditions: IDropClaimCondition_V2.ClaimConditionStructOutput[]
  ];
  export interface OutputObject {
    tokenId: bigint;
    claimConditions: IDropClaimCondition_V2.ClaimConditionStructOutput[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MaxTotalSupplyUpdatedEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    maxTotalSupply: BigNumberish
  ];
  export type OutputTuple = [tokenId: bigint, maxTotalSupply: bigint];
  export interface OutputObject {
    tokenId: bigint;
    maxTotalSupply: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MaxWalletClaimCountUpdatedEvent {
  export type InputTuple = [tokenId: BigNumberish, count: BigNumberish];
  export type OutputTuple = [tokenId: bigint, count: bigint];
  export interface OutputObject {
    tokenId: bigint;
    count: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SaleRecipientForTokenUpdatedEvent {
  export type InputTuple = [tokenId: BigNumberish, saleRecipient: AddressLike];
  export type OutputTuple = [tokenId: bigint, saleRecipient: string];
  export interface OutputObject {
    tokenId: bigint;
    saleRecipient: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokensClaimedEvent {
  export type InputTuple = [
    claimConditionIndex: BigNumberish,
    tokenId: BigNumberish,
    claimer: AddressLike,
    receiver: AddressLike,
    quantityClaimed: BigNumberish
  ];
  export type OutputTuple = [
    claimConditionIndex: bigint,
    tokenId: bigint,
    claimer: string,
    receiver: string,
    quantityClaimed: bigint
  ];
  export interface OutputObject {
    claimConditionIndex: bigint;
    tokenId: bigint;
    claimer: string;
    receiver: string;
    quantityClaimed: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokensLazyMintedEvent {
  export type InputTuple = [
    startTokenId: BigNumberish,
    endTokenId: BigNumberish,
    baseURI: string
  ];
  export type OutputTuple = [
    startTokenId: bigint,
    endTokenId: bigint,
    baseURI: string
  ];
  export interface OutputObject {
    startTokenId: bigint;
    endTokenId: bigint;
    baseURI: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferBatchEvent {
  export type InputTuple = [
    operator: AddressLike,
    from: AddressLike,
    to: AddressLike,
    ids: BigNumberish[],
    values: BigNumberish[]
  ];
  export type OutputTuple = [
    operator: string,
    from: string,
    to: string,
    ids: bigint[],
    values: bigint[]
  ];
  export interface OutputObject {
    operator: string;
    from: string;
    to: string;
    ids: bigint[];
    values: bigint[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferSingleEvent {
  export type InputTuple = [
    operator: AddressLike,
    from: AddressLike,
    to: AddressLike,
    id: BigNumberish,
    value: BigNumberish
  ];
  export type OutputTuple = [
    operator: string,
    from: string,
    to: string,
    id: bigint,
    value: bigint
  ];
  export interface OutputObject {
    operator: string;
    from: string;
    to: string;
    id: bigint;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace URIEvent {
  export type InputTuple = [value: string, id: BigNumberish];
  export type OutputTuple = [value: string, id: bigint];
  export interface OutputObject {
    value: string;
    id: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WalletClaimCountUpdatedEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    wallet: AddressLike,
    count: BigNumberish
  ];
  export type OutputTuple = [tokenId: bigint, wallet: string, count: bigint];
  export interface OutputObject {
    tokenId: bigint;
    wallet: string;
    count: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IDropERC1155_V2 extends BaseContract {
  connect(runner?: ContractRunner | null): IDropERC1155_V2;
  waitForDeployment(): Promise<this>;

  interface: IDropERC1155_V2Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  balanceOf: TypedContractMethod<
    [account: AddressLike, id: BigNumberish],
    [bigint],
    "view"
  >;

  balanceOfBatch: TypedContractMethod<
    [accounts: AddressLike[], ids: BigNumberish[]],
    [bigint[]],
    "view"
  >;

  claim: TypedContractMethod<
    [
      receiver: AddressLike,
      tokenId: BigNumberish,
      quantity: BigNumberish,
      currency: AddressLike,
      pricePerToken: BigNumberish,
      proofs: BytesLike[],
      proofMaxQuantityPerTransaction: BigNumberish
    ],
    [void],
    "payable"
  >;

  isApprovedForAll: TypedContractMethod<
    [account: AddressLike, operator: AddressLike],
    [boolean],
    "view"
  >;

  lazyMint: TypedContractMethod<
    [amount: BigNumberish, baseURIForTokens: string],
    [void],
    "nonpayable"
  >;

  safeBatchTransferFrom: TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      ids: BigNumberish[],
      amounts: BigNumberish[],
      data: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  safeTransferFrom: TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      id: BigNumberish,
      amount: BigNumberish,
      data: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  setApprovalForAll: TypedContractMethod<
    [operator: AddressLike, approved: boolean],
    [void],
    "nonpayable"
  >;

  setClaimConditions: TypedContractMethod<
    [
      tokenId: BigNumberish,
      phases: IDropClaimCondition_V2.ClaimConditionStruct[],
      resetClaimEligibility: boolean
    ],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "balanceOf"
  ): TypedContractMethod<
    [account: AddressLike, id: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "balanceOfBatch"
  ): TypedContractMethod<
    [accounts: AddressLike[], ids: BigNumberish[]],
    [bigint[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "claim"
  ): TypedContractMethod<
    [
      receiver: AddressLike,
      tokenId: BigNumberish,
      quantity: BigNumberish,
      currency: AddressLike,
      pricePerToken: BigNumberish,
      proofs: BytesLike[],
      proofMaxQuantityPerTransaction: BigNumberish
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "isApprovedForAll"
  ): TypedContractMethod<
    [account: AddressLike, operator: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "lazyMint"
  ): TypedContractMethod<
    [amount: BigNumberish, baseURIForTokens: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "safeBatchTransferFrom"
  ): TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      ids: BigNumberish[],
      amounts: BigNumberish[],
      data: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "safeTransferFrom"
  ): TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      id: BigNumberish,
      amount: BigNumberish,
      data: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setApprovalForAll"
  ): TypedContractMethod<
    [operator: AddressLike, approved: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setClaimConditions"
  ): TypedContractMethod<
    [
      tokenId: BigNumberish,
      phases: IDropClaimCondition_V2.ClaimConditionStruct[],
      resetClaimEligibility: boolean
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;

  getEvent(
    key: "ApprovalForAll"
  ): TypedContractEvent<
    ApprovalForAllEvent.InputTuple,
    ApprovalForAllEvent.OutputTuple,
    ApprovalForAllEvent.OutputObject
  >;
  getEvent(
    key: "ClaimConditionsUpdated"
  ): TypedContractEvent<
    ClaimConditionsUpdatedEvent.InputTuple,
    ClaimConditionsUpdatedEvent.OutputTuple,
    ClaimConditionsUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "MaxTotalSupplyUpdated"
  ): TypedContractEvent<
    MaxTotalSupplyUpdatedEvent.InputTuple,
    MaxTotalSupplyUpdatedEvent.OutputTuple,
    MaxTotalSupplyUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "MaxWalletClaimCountUpdated"
  ): TypedContractEvent<
    MaxWalletClaimCountUpdatedEvent.InputTuple,
    MaxWalletClaimCountUpdatedEvent.OutputTuple,
    MaxWalletClaimCountUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "SaleRecipientForTokenUpdated"
  ): TypedContractEvent<
    SaleRecipientForTokenUpdatedEvent.InputTuple,
    SaleRecipientForTokenUpdatedEvent.OutputTuple,
    SaleRecipientForTokenUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "TokensClaimed"
  ): TypedContractEvent<
    TokensClaimedEvent.InputTuple,
    TokensClaimedEvent.OutputTuple,
    TokensClaimedEvent.OutputObject
  >;
  getEvent(
    key: "TokensLazyMinted"
  ): TypedContractEvent<
    TokensLazyMintedEvent.InputTuple,
    TokensLazyMintedEvent.OutputTuple,
    TokensLazyMintedEvent.OutputObject
  >;
  getEvent(
    key: "TransferBatch"
  ): TypedContractEvent<
    TransferBatchEvent.InputTuple,
    TransferBatchEvent.OutputTuple,
    TransferBatchEvent.OutputObject
  >;
  getEvent(
    key: "TransferSingle"
  ): TypedContractEvent<
    TransferSingleEvent.InputTuple,
    TransferSingleEvent.OutputTuple,
    TransferSingleEvent.OutputObject
  >;
  getEvent(
    key: "URI"
  ): TypedContractEvent<
    URIEvent.InputTuple,
    URIEvent.OutputTuple,
    URIEvent.OutputObject
  >;
  getEvent(
    key: "WalletClaimCountUpdated"
  ): TypedContractEvent<
    WalletClaimCountUpdatedEvent.InputTuple,
    WalletClaimCountUpdatedEvent.OutputTuple,
    WalletClaimCountUpdatedEvent.OutputObject
  >;

  filters: {
    "ApprovalForAll(address,address,bool)": TypedContractEvent<
      ApprovalForAllEvent.InputTuple,
      ApprovalForAllEvent.OutputTuple,
      ApprovalForAllEvent.OutputObject
    >;
    ApprovalForAll: TypedContractEvent<
      ApprovalForAllEvent.InputTuple,
      ApprovalForAllEvent.OutputTuple,
      ApprovalForAllEvent.OutputObject
    >;

    "ClaimConditionsUpdated(uint256,tuple[])": TypedContractEvent<
      ClaimConditionsUpdatedEvent.InputTuple,
      ClaimConditionsUpdatedEvent.OutputTuple,
      ClaimConditionsUpdatedEvent.OutputObject
    >;
    ClaimConditionsUpdated: TypedContractEvent<
      ClaimConditionsUpdatedEvent.InputTuple,
      ClaimConditionsUpdatedEvent.OutputTuple,
      ClaimConditionsUpdatedEvent.OutputObject
    >;

    "MaxTotalSupplyUpdated(uint256,uint256)": TypedContractEvent<
      MaxTotalSupplyUpdatedEvent.InputTuple,
      MaxTotalSupplyUpdatedEvent.OutputTuple,
      MaxTotalSupplyUpdatedEvent.OutputObject
    >;
    MaxTotalSupplyUpdated: TypedContractEvent<
      MaxTotalSupplyUpdatedEvent.InputTuple,
      MaxTotalSupplyUpdatedEvent.OutputTuple,
      MaxTotalSupplyUpdatedEvent.OutputObject
    >;

    "MaxWalletClaimCountUpdated(uint256,uint256)": TypedContractEvent<
      MaxWalletClaimCountUpdatedEvent.InputTuple,
      MaxWalletClaimCountUpdatedEvent.OutputTuple,
      MaxWalletClaimCountUpdatedEvent.OutputObject
    >;
    MaxWalletClaimCountUpdated: TypedContractEvent<
      MaxWalletClaimCountUpdatedEvent.InputTuple,
      MaxWalletClaimCountUpdatedEvent.OutputTuple,
      MaxWalletClaimCountUpdatedEvent.OutputObject
    >;

    "SaleRecipientForTokenUpdated(uint256,address)": TypedContractEvent<
      SaleRecipientForTokenUpdatedEvent.InputTuple,
      SaleRecipientForTokenUpdatedEvent.OutputTuple,
      SaleRecipientForTokenUpdatedEvent.OutputObject
    >;
    SaleRecipientForTokenUpdated: TypedContractEvent<
      SaleRecipientForTokenUpdatedEvent.InputTuple,
      SaleRecipientForTokenUpdatedEvent.OutputTuple,
      SaleRecipientForTokenUpdatedEvent.OutputObject
    >;

    "TokensClaimed(uint256,uint256,address,address,uint256)": TypedContractEvent<
      TokensClaimedEvent.InputTuple,
      TokensClaimedEvent.OutputTuple,
      TokensClaimedEvent.OutputObject
    >;
    TokensClaimed: TypedContractEvent<
      TokensClaimedEvent.InputTuple,
      TokensClaimedEvent.OutputTuple,
      TokensClaimedEvent.OutputObject
    >;

    "TokensLazyMinted(uint256,uint256,string)": TypedContractEvent<
      TokensLazyMintedEvent.InputTuple,
      TokensLazyMintedEvent.OutputTuple,
      TokensLazyMintedEvent.OutputObject
    >;
    TokensLazyMinted: TypedContractEvent<
      TokensLazyMintedEvent.InputTuple,
      TokensLazyMintedEvent.OutputTuple,
      TokensLazyMintedEvent.OutputObject
    >;

    "TransferBatch(address,address,address,uint256[],uint256[])": TypedContractEvent<
      TransferBatchEvent.InputTuple,
      TransferBatchEvent.OutputTuple,
      TransferBatchEvent.OutputObject
    >;
    TransferBatch: TypedContractEvent<
      TransferBatchEvent.InputTuple,
      TransferBatchEvent.OutputTuple,
      TransferBatchEvent.OutputObject
    >;

    "TransferSingle(address,address,address,uint256,uint256)": TypedContractEvent<
      TransferSingleEvent.InputTuple,
      TransferSingleEvent.OutputTuple,
      TransferSingleEvent.OutputObject
    >;
    TransferSingle: TypedContractEvent<
      TransferSingleEvent.InputTuple,
      TransferSingleEvent.OutputTuple,
      TransferSingleEvent.OutputObject
    >;

    "URI(string,uint256)": TypedContractEvent<
      URIEvent.InputTuple,
      URIEvent.OutputTuple,
      URIEvent.OutputObject
    >;
    URI: TypedContractEvent<
      URIEvent.InputTuple,
      URIEvent.OutputTuple,
      URIEvent.OutputObject
    >;

    "WalletClaimCountUpdated(uint256,address,uint256)": TypedContractEvent<
      WalletClaimCountUpdatedEvent.InputTuple,
      WalletClaimCountUpdatedEvent.OutputTuple,
      WalletClaimCountUpdatedEvent.OutputObject
    >;
    WalletClaimCountUpdated: TypedContractEvent<
      WalletClaimCountUpdatedEvent.InputTuple,
      WalletClaimCountUpdatedEvent.OutputTuple,
      WalletClaimCountUpdatedEvent.OutputObject
    >;
  };
}
