/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ERC1155Holder__factory } from "./ERC1155Holder__factory";
export { ERC1155Receiver__factory } from "./ERC1155Receiver__factory";
