/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../../common";

export declare namespace IAirdropERC20 {
  export type AirdropContentStruct = {
    recipient: AddressLike;
    amount: BigNumberish;
  };

  export type AirdropContentStructOutput = [
    recipient: string,
    amount: bigint
  ] & { recipient: string; amount: bigint };
}

export interface IAirdropERC20Interface extends Interface {
  getFunction(nameOrSignature: "airdropERC20"): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "AirdropFailed"): EventFragment;

  encodeFunctionData(
    functionFragment: "airdropERC20",
    values: [AddressLike, AddressLike, IAirdropERC20.AirdropContentStruct[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "airdropERC20",
    data: BytesLike
  ): Result;
}

export namespace AirdropFailedEvent {
  export type InputTuple = [
    tokenAddress: AddressLike,
    tokenOwner: AddressLike,
    recipient: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    tokenAddress: string,
    tokenOwner: string,
    recipient: string,
    amount: bigint
  ];
  export interface OutputObject {
    tokenAddress: string;
    tokenOwner: string;
    recipient: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IAirdropERC20 extends BaseContract {
  connect(runner?: ContractRunner | null): IAirdropERC20;
  waitForDeployment(): Promise<this>;

  interface: IAirdropERC20Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  airdropERC20: TypedContractMethod<
    [
      tokenAddress: AddressLike,
      tokenOwner: AddressLike,
      contents: IAirdropERC20.AirdropContentStruct[]
    ],
    [void],
    "payable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "airdropERC20"
  ): TypedContractMethod<
    [
      tokenAddress: AddressLike,
      tokenOwner: AddressLike,
      contents: IAirdropERC20.AirdropContentStruct[]
    ],
    [void],
    "payable"
  >;

  getEvent(
    key: "AirdropFailed"
  ): TypedContractEvent<
    AirdropFailedEvent.InputTuple,
    AirdropFailedEvent.OutputTuple,
    AirdropFailedEvent.OutputObject
  >;

  filters: {
    "AirdropFailed(address,address,address,uint256)": TypedContractEvent<
      AirdropFailedEvent.InputTuple,
      AirdropFailedEvent.OutputTuple,
      AirdropFailedEvent.OutputObject
    >;
    AirdropFailed: TypedContractEvent<
      AirdropFailedEvent.InputTuple,
      AirdropFailedEvent.OutputTuple,
      AirdropFailedEvent.OutputObject
    >;
  };
}
