/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BurnToClaim } from "./BurnToClaim";
export type { BurnToClaimStorage } from "./BurnToClaimStorage";
