/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { PlatformFee } from "./PlatformFee";
export type { PlatformFeeStorage } from "./PlatformFeeStorage";
