/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../../common";

export declare namespace IPluginMap {
  export type PluginStruct = {
    functionSelector: BytesLike;
    functionSignature: string;
    pluginAddress: AddressLike;
  };

  export type PluginStructOutput = [
    functionSelector: string,
    functionSignature: string,
    pluginAddress: string
  ] & {
    functionSelector: string;
    functionSignature: string;
    pluginAddress: string;
  };
}

export interface TWMultichainRegistryRouterInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_ADMIN_ROLE"
      | "_getPluginForFunction"
      | "addPlugin"
      | "getAllFunctionsOfPlugin"
      | "getAllPlugins"
      | "getPluginForFunction"
      | "getRoleAdmin"
      | "getRoleMember"
      | "getRoleMemberCount"
      | "grantRole"
      | "hasRole"
      | "hasRoleWithSwitch"
      | "isTrustedForwarder"
      | "multicall"
      | "pluginMap"
      | "removePlugin"
      | "renounceRole"
      | "revokeRole"
      | "supportsInterface"
      | "updatePlugin"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "PluginAdded"
      | "PluginRemoved"
      | "PluginSet"
      | "PluginUpdated"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "_getPluginForFunction",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "addPlugin",
    values: [IPluginMap.PluginStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllFunctionsOfPlugin",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllPlugins",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPluginForFunction",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleMember",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleMemberCount",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRoleWithSwitch",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isTrustedForwarder",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "multicall",
    values: [BytesLike[]]
  ): string;
  encodeFunctionData(functionFragment: "pluginMap", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "removePlugin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updatePlugin",
    values: [IPluginMap.PluginStruct]
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_getPluginForFunction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addPlugin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAllFunctionsOfPlugin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllPlugins",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPluginForFunction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleMember",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleMemberCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hasRoleWithSwitch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isTrustedForwarder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "multicall", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pluginMap", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removePlugin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updatePlugin",
    data: BytesLike
  ): Result;
}

export namespace PluginAddedEvent {
  export type InputTuple = [
    functionSelector: BytesLike,
    pluginAddress: AddressLike
  ];
  export type OutputTuple = [functionSelector: string, pluginAddress: string];
  export interface OutputObject {
    functionSelector: string;
    pluginAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PluginRemovedEvent {
  export type InputTuple = [
    functionSelector: BytesLike,
    pluginAddress: AddressLike
  ];
  export type OutputTuple = [functionSelector: string, pluginAddress: string];
  export interface OutputObject {
    functionSelector: string;
    pluginAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PluginSetEvent {
  export type InputTuple = [
    functionSelector: BytesLike,
    functionSignature: string,
    pluginAddress: AddressLike
  ];
  export type OutputTuple = [
    functionSelector: string,
    functionSignature: string,
    pluginAddress: string
  ];
  export interface OutputObject {
    functionSelector: string;
    functionSignature: string;
    pluginAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PluginUpdatedEvent {
  export type InputTuple = [
    functionSelector: BytesLike,
    oldPluginAddress: AddressLike,
    newPluginAddress: AddressLike
  ];
  export type OutputTuple = [
    functionSelector: string,
    oldPluginAddress: string,
    newPluginAddress: string
  ];
  export interface OutputObject {
    functionSelector: string;
    oldPluginAddress: string;
    newPluginAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TWMultichainRegistryRouter extends BaseContract {
  connect(runner?: ContractRunner | null): TWMultichainRegistryRouter;
  waitForDeployment(): Promise<this>;

  interface: TWMultichainRegistryRouterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  _getPluginForFunction: TypedContractMethod<
    [_selector: BytesLike],
    [string],
    "view"
  >;

  addPlugin: TypedContractMethod<
    [_plugin: IPluginMap.PluginStruct],
    [void],
    "nonpayable"
  >;

  getAllFunctionsOfPlugin: TypedContractMethod<
    [_pluginAddress: AddressLike],
    [string[]],
    "view"
  >;

  getAllPlugins: TypedContractMethod<
    [],
    [IPluginMap.PluginStructOutput[]],
    "view"
  >;

  getPluginForFunction: TypedContractMethod<
    [_selector: BytesLike],
    [string],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  getRoleMember: TypedContractMethod<
    [role: BytesLike, index: BigNumberish],
    [string],
    "view"
  >;

  getRoleMemberCount: TypedContractMethod<[role: BytesLike], [bigint], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  hasRoleWithSwitch: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  isTrustedForwarder: TypedContractMethod<
    [forwarder: AddressLike],
    [boolean],
    "view"
  >;

  multicall: TypedContractMethod<[data: BytesLike[]], [string[]], "nonpayable">;

  pluginMap: TypedContractMethod<[], [string], "view">;

  removePlugin: TypedContractMethod<
    [_selector: BytesLike],
    [void],
    "nonpayable"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  updatePlugin: TypedContractMethod<
    [_plugin: IPluginMap.PluginStruct],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "_getPluginForFunction"
  ): TypedContractMethod<[_selector: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "addPlugin"
  ): TypedContractMethod<
    [_plugin: IPluginMap.PluginStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAllFunctionsOfPlugin"
  ): TypedContractMethod<[_pluginAddress: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getAllPlugins"
  ): TypedContractMethod<[], [IPluginMap.PluginStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "getPluginForFunction"
  ): TypedContractMethod<[_selector: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getRoleMember"
  ): TypedContractMethod<
    [role: BytesLike, index: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRoleMemberCount"
  ): TypedContractMethod<[role: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasRoleWithSwitch"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isTrustedForwarder"
  ): TypedContractMethod<[forwarder: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "multicall"
  ): TypedContractMethod<[data: BytesLike[]], [string[]], "nonpayable">;
  getFunction(
    nameOrSignature: "pluginMap"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "removePlugin"
  ): TypedContractMethod<[_selector: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "updatePlugin"
  ): TypedContractMethod<
    [_plugin: IPluginMap.PluginStruct],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "PluginAdded"
  ): TypedContractEvent<
    PluginAddedEvent.InputTuple,
    PluginAddedEvent.OutputTuple,
    PluginAddedEvent.OutputObject
  >;
  getEvent(
    key: "PluginRemoved"
  ): TypedContractEvent<
    PluginRemovedEvent.InputTuple,
    PluginRemovedEvent.OutputTuple,
    PluginRemovedEvent.OutputObject
  >;
  getEvent(
    key: "PluginSet"
  ): TypedContractEvent<
    PluginSetEvent.InputTuple,
    PluginSetEvent.OutputTuple,
    PluginSetEvent.OutputObject
  >;
  getEvent(
    key: "PluginUpdated"
  ): TypedContractEvent<
    PluginUpdatedEvent.InputTuple,
    PluginUpdatedEvent.OutputTuple,
    PluginUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;

  filters: {
    "PluginAdded(bytes4,address)": TypedContractEvent<
      PluginAddedEvent.InputTuple,
      PluginAddedEvent.OutputTuple,
      PluginAddedEvent.OutputObject
    >;
    PluginAdded: TypedContractEvent<
      PluginAddedEvent.InputTuple,
      PluginAddedEvent.OutputTuple,
      PluginAddedEvent.OutputObject
    >;

    "PluginRemoved(bytes4,address)": TypedContractEvent<
      PluginRemovedEvent.InputTuple,
      PluginRemovedEvent.OutputTuple,
      PluginRemovedEvent.OutputObject
    >;
    PluginRemoved: TypedContractEvent<
      PluginRemovedEvent.InputTuple,
      PluginRemovedEvent.OutputTuple,
      PluginRemovedEvent.OutputObject
    >;

    "PluginSet(bytes4,string,address)": TypedContractEvent<
      PluginSetEvent.InputTuple,
      PluginSetEvent.OutputTuple,
      PluginSetEvent.OutputObject
    >;
    PluginSet: TypedContractEvent<
      PluginSetEvent.InputTuple,
      PluginSetEvent.OutputTuple,
      PluginSetEvent.OutputObject
    >;

    "PluginUpdated(bytes4,address,address)": TypedContractEvent<
      PluginUpdatedEvent.InputTuple,
      PluginUpdatedEvent.OutputTuple,
      PluginUpdatedEvent.OutputObject
    >;
    PluginUpdated: TypedContractEvent<
      PluginUpdatedEvent.InputTuple,
      PluginUpdatedEvent.OutputTuple,
      PluginUpdatedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
  };
}
