/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC1155HolderUpgradeable } from "./ERC1155HolderUpgradeable";
export type { ERC1155ReceiverUpgradeable } from "./ERC1155ReceiverUpgradeable";
