/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Permissions } from "./Permissions";
export type { PermissionsStorage } from "./PermissionsStorage";
