/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IDropERC1155__factory } from "./IDropERC1155__factory";
export { IDropERC20__factory } from "./IDropERC20__factory";
export { IDropERC721__factory } from "./IDropERC721__factory";
